name: Verify GCP Service Account

on:
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  verify-service-account:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Authenticate with Google Cloud using the service account
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Set up Google Cloud SDK
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Debug the secret content
    - name: 'Debug Service Account Key'
      run: |
        echo "Raw secret content:"
        echo "${{ secrets.GCP_SA_KEY }}"
        echo "Writing to key.json..."
        printf '%s' "${{ secrets.GCP_SA_KEY }}" > key.json
        echo "Content of key.json:"
        cat key.json
        echo "Validating JSON..."
        jq . key.json || echo "JSON validation failed"

    # Verify authentication by listing active accounts
    - name: 'Check Active Account'
      run: |
        echo "Listing active Google Cloud accounts..."
        gcloud auth list
        echo "Expected active account: gcp-adhoc-shutdown-sa@buoyant-facet-448415-n4.iam.gserviceaccount.com"

    # Verify gcloud CLI functionality
    - name: 'Run gcloud Info'
      run: |
        echo "Displaying gcloud environment info..."
        gcloud info