name: Stop GCP VM

on:
    workflow_dispatch:
    jobs:
        stop-vm:
            runs-on: ubuntu-latest

            steps:
            - name: Set up Google Cloud SDK
                uses: google-github-actions/setup-gcloud@v1
                with:
                    project_id: ${{ secrets.GCP_PROJECT_ID }}
                    service_account_key: ${{ secrets.GCP_SA_KEY }}

            - name: Stop GCP VM
                run: |
                    gcloud compute instances stop ${{ secrets.GCP_VM_NAME }} \
                        --zone ${{ secrets.GCP_ZONE }}
