name: GCP VM Schedule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up key.json
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > key.json

      - name: Validate JSON
        run: jq . key.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=key.json